#!/bin/python

"""
Description:
    Name: Text (TermuxToolkit)
    Tool: Paste your Text
    Author: OmniTotal
    GitHub: https://github.com/toxic-noob
    Version: 1.0

Uses:
    This tool has two arguments:
        -t / --text
        -f / --file
    
    -t / --text:
        Use this Argument to Paste some text. Example:
            text -t "This is a Text"
    
    -f / --file:
        Use this Argument to Paste texts of Any File. Example:
            text -f /path/to/your/file.txt
    
"""

import os
import subprocess as sb
from helpscript import argparser

def paste(pasteData, type="text"):
    if (type == "file"):
        if not os.path.exists(pasteData):
            print("\n[\033[91m!\033[37m] File not Found!\n")
            exit()
        
        pasteData = open(pasteData, "r").read()
    
    print("\n[\033[92m*\033[37m] Uploading Your Paste: ", end = "")
   
    import requests
    headers = {
        "Host": "snippet.host",
        "cache-control": "max-age=0",
        "upgrade-insecure-requests": "1",
        "origin": "https://snippet.host",
        "content-type": "multipart/form-data; boundary=----WebKitFormBoundaryBiX583G3giu5SXUS",
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "sec-gpc": "1",
        "sec-fetch-site": "same-origin",
        "sec-fetch-mode": "navigate",
        "sec-fetch-user": "?1",
        "sec-fetch-dest": "document",
        "referer": "https://snippet.host/",
        "accept-language": "en-US,en;q=0.9",
    }
    
    data = f"------WebKitFormBoundaryBiX583G3giu5SXUS\r\nContent-Disposition: form-data; name=title\r\n\r\n\r\n------WebKitFormBoundaryBiX583G3giu5SXUS\r\nContent-Disposition: form-data; name=content\r\n\r\n{pasteData}\r\n------WebKitFormBoundaryBiX583G3giu5SXUS\r\nContent-Disposition: form-data; name=visibility\r\n\r\n2\r\n------WebKitFormBoundaryBiX583G3giu5SXUS\r\nContent-Disposition: form-data; name=expires\r\n\r\nnever\r\n------WebKitFormBoundaryBiX583G3giu5SXUS\r\nContent-Disposition: form-data; name=language\r\n\r\nplain text\r\n------WebKitFormBoundaryBiX583G3giu5SXUS\r\nContent-Disposition: form-data; name=js\r\n\r\nfalse\r\n------WebKitFormBoundaryBiX583G3giu5SXUS--\r\n"
    
    url = "https://snippet.host/"
    
    response = requests.post(url, headers=headers, data=data)
   
    if (response.status_code != 200) or (response.url == "https://snippet.host/"):
        print("Error")
        print("\n[\033[91m!\033[37m] Error Occured while Pasting\n")
        print(response)
        exit()
    
    print("Done")
    print("\n[\033[92m*\033[37m] Paste Url: " + response.url)
    print("\n[\033[92m*\033[37m] Raw Url: " + response.url + "/raw")
    exit("")

if (__name__ == "__main__"):
    parser = argparser()
    parser.add_argument(("-t", "--text"), "text", required = "optional", help = "Use this Argument to Enter your text")
    parser.add_argument(("-f", "--file"), "file", required = "optional",  help = "Use this Argument to Enter your File")
    
    args = parser.parsed()
    
    if (args.text):
        paste(args.text, type = "text")
        
    elif (args.file):
        paste(args.file, type = "file")




